# Generated by Django 3.0.7 on 2020-12-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='applicants',
        ),
    ]
