# Generated by Django 3.1.3 on 2020-12-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='applicants',
        ),
        migrations.AddField(
            model_name='club',
            name='click_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='upload',
            field=models.ImageField(default='blog/club/', upload_to='blog/club/'),
        ),
        migrations.AddField(
            model_name='events',
            name='upload',
            field=models.ImageField(default='blog/events/', upload_to='blog/events/'),
        ),
    ]
