# Generated by Django 3.1.3 on 2021-07-22 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('official_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('upload', models.ImageField(default='blog/campus/', upload_to='blog/campus/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('upload', models.ImageField(default='blog/dep/', upload_to='blog/dep/')),
                ('official_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('upload', models.ImageField(default='blog/events/', upload_to='blog/events/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='applicants',
        ),
        migrations.AddField(
            model_name='club',
            name='click_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='upload',
            field=models.ImageField(default='blog/club/', upload_to='blog/club/'),
        ),
        migrations.AddField(
            model_name='events',
            name='upload',
            field=models.ImageField(default='blog/events/', upload_to='blog/events/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reg_no',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
