# Generated by Django 3.0.7 on 2020-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0002_remove_field_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='click_link',
            field=models.TextField(blank=True),
        ),
    ]
