# Generated by Django 3.0.7 on 2020-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0003_club_click_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='upload',
            field=models.ImageField(default='blog/pics/', upload_to='blog/pics/'),
        ),
    ]
