# Generated by Django 3.0.7 on 2020-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0004_club_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='upload',
            field=models.ImageField(default='blog/club/', upload_to='blog/club/'),
        ),
    ]
