# Generated by Django 3.1.3 on 2020-12-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0005_auto_20201213_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='upload',
            field=models.ImageField(default='blog/events/', upload_to='blog/events/'),
        ),
    ]
