# Generated by Django 3.0.7 on 2020-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0007_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('upload', models.ImageField(default='blog/campus/', upload_to='blog/campus/')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='upload',
            field=models.ImageField(default='blog/dep/', upload_to='blog/dep/'),
        ),
    ]
