# Generated by Django 3.1.3 on 2020-12-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0010_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('upload', models.ImageField(default='blog/events/', upload_to='blog/events/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
