# Generated by Django 3.1.3 on 2021-01-16 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0011_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
